services:
  mongo:
    image: 'mongo'
    container_name: 'mongo'
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  redis:
    image: 'redis:alpine'
    container_name: 'redis'
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - ./redis-data:/data

  app:
    build: .
    container_name: 'node-app'
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URL=mongodb://mongo:27017/nest
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongo-data:
  redis-data:
